### ISSUE TITLE
Source licensing question

### ISSUE THREAD

**Issue by DeepUpSonnemann** [Adjam93/WebGl-Three.js-.obj-Model-Viewer#2]
The project does not contain any licensing information as far as I could find.

Would you consider an open-source license?

**Comment by Adjam93** [comment]
Hello,

Yes the project is fully open-source for anyone to use. I just added an MIT license for the sake of clarity.

The project and code is fairly old by now and probably could do with improving anyway, but I believe it still works as intended in its current state, thanks 👍

**Comment by DeepUpSonnemann** [comment]
It's a great jump-off point for me to understand how everything fits together. The tutorials I found were always missing a crucial point. Thank you for this project!
